# Generated by Django 2.1.7 on 2019-02-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190212_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='content',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
